name: Cypress Tests

on:
  push:
    branches: [ main, master, cypress_github ]
  pull_request:
    branches: [ main, master, cypress_github ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
        env:
          CYPRESS_BASE_URL: https://qauto.forstudy.space
          CYPRESS_USER: guest
          CYPRESS_PASSWORD: welcome2qauto
          CYPRESS_userEmail: "test_prod@example.com"
          CYPRESS_userPassword: "6WiiW!9LTxAQBWW"